const SERIES_UNITS={userDeclaredPowerMw:'MW',defaultDeclaredPowerMw:'MW',dayAheadUserClearedPowerMw:'MW',actualAverageLoadMw:'MW',systemLoadForecastMw:'MW',netLoadForecastMw:'MW',dayAheadUserPriceTemporaryYuanPerMwh:'元/MWh',dayAheadUserPriceFinalYuanPerMwh:'元/MWh',realTimePriceCurrentYuanPerMwh:'元/MWh',realTimePriceFinalYuanPerMwh:'元/MWh'};
function missing(fieldId,unit='MW'){return{value:null,unit,mode:'real',fieldId,qualityStatus:'missing',missingReason:'source_not_confirmed'};}
export function buildMarketCockpit({snapshot={},marketContext=[],forecasts=[],events=[],mode='real'}={}){
  const rows=snapshot.rows||[], series={};
  for(const [fieldId,unit] of Object.entries(SERIES_UNITS)){series[fieldId]={fieldId,unit,mode,commonProvenance:{featureSnapshotId:snapshot.featureSnapshotId||null,decisionCutoffAt:snapshot.decisionCutoffAt||null},points:rows.map(row=>({pointIndex:row.pointIndex,value:row.fields?.[fieldId]??null,qualityStatus:row.fields?.[fieldId]===undefined?'missing':'confirmed',...(row.fields?.[fieldId]===undefined?{missingReason:'source_not_confirmed'}:{}),provenanceOverride:{factIds:row.selectedFactIds||[]}}))};}
  const first=(fieldId)=>rows.find(row=>row.fields?.[fieldId]!==undefined)?.fields[fieldId]??null, metric=(fieldId,unit='MW')=>{const value=first(fieldId);return value===null?missing(fieldId,unit):{value,unit,mode,fieldId,qualityStatus:'confirmed',sourceId:'point-in-time-store',availableAt:snapshot.decisionCutoffAt,revision:snapshot.contentHash,evidenceRef:`feature:${snapshot.featureSnapshotId}:${fieldId}`};};
  const metrics={availableCapacityMw:metric('availableCapacityMw'),userLoad:metric('actualAverageLoadMw'),netLoad:metric('netLoadForecastMw'),renewables:metric('windForecastMw'),interchange:metric('interchangeScheduledImportMw'),network:metric('sectionUtilizationPct','%'),dayAheadPrice:metric('dayAheadUserPriceFinalYuanPerMwh','元/MWh'),realTimePrice:metric('realTimePriceFinalYuanPerMwh','元/MWh'),risk:missing('marketRisk','')};
  const gaps=Object.values(metrics).filter(item=>item.value===null).map(item=>({fieldId:item.fieldId,reason:item.missingReason,evidenceRef:null}));
  return{identity:{targetDate:snapshot.targetDate||null,asOf:snapshot.decisionCutoffAt||null,marketStage:'decision_support',mode,completeness:Math.round((1-gaps.length/Object.keys(metrics).length)*100)},mode,quality:{completeness:Math.round((1-gaps.length/Object.keys(metrics).length)*100),gaps},metrics,series,demand:{},weather:{},supply:{},network:{},price:{},position:{},marketContext,forecasts,events,gaps,executionAllowed:false};
}
